const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  gymlogo: state => state.user.gym_logo,
  gymname: state => state.errorLog.gym_name,
  userName: state => state.user.userName,
  userPassword: state => state.user.userPassword,
  gym_id: state => state.user.gym_id,
  gymsList: state => state.manageGyms.gymsList,
  activeDateDesktop: state => state.manageGyms.activeDateDesktop,
  saasVersion: state => state.manageGyms.saasVersion,
}
export default getters
